// Generated by   : ImageConverter 565 Online
// Generated from : Screenshot_20250719_213804.png
// Time generated : Sat, 19 Jul 25 16:41:10 +0200  (Server timezone: CET)
// Image Size     : 240x240 pixels
// Memory usage   : 115200 bytes

#ifndef HUC_H
#define HUC_H

#include <stdint.h>

extern const unsigned short huc[57600];
#endif